define(['jquery', 'widget!tm/widgets/tooltip', 'widget!tm/widgets/popup'], function($) {
    'use strict';

    var data = {
        legend: 'Overview',
        description: 'Tooltips appear on element hover.',
        html:'\
            <div id="overview-non-modal-container" class="demo-container">\n\
                <p><a id="tooltipTarget" \n\
                    title="It\'s so simple to create a tooltip!"\n\
                    data-placement="top">Tooltip</a></p>\n\
                <p><a href="#" title="System tooltips are slow to appear and don\'t look as good.">System Tooltip</a>\n\
                    (generated by the browser when an element has a \"title\" property)</p>\n\
            </div>',
        js: function() {
            $("#tooltipTarget").tmTooltip();
        }
    };

    return data;
});