/******************************************************************
 Include spec files here...
******************************************************************/
define([
    'spec/tm/cookieSpec.js',
    'spec/tm/widgets/widgetFactory-spec',
    'spec/tm/widgets/primaryButton-spec',
    'spec/tm/widgets/secondaryButton-spec',
    'spec/tm/widgets/importantButton-spec',
    'spec/tm/widgets/modalDialog-spec',
    'spec/tm/widgets/radioButton-spec',
    'spec/tm/widgets/checkbox-spec',
    'spec/tm/widgets/dropdownButtonMenu-spec',
    'spec/tm/widgets/dropdown-spec',
    'spec/tm/widgets/popup-spec',
    'spec/tm/widgets/tabbedContainer-spec',
    'spec/tm/widgets/textInputField-spec',
    'spec/tm/widgets/searchAndFilter-spec',
    'spec/tm/widgets/backToTopButton-spec',
    'spec/tm/errorDialog-spec'
]);